[package]
name = "multi-drop-bus"
version = "0.1.0-canary"
edition = "2021"

[dependencies]
deku = { version = "0.15.0" }
flagset = "0.4.3"

[dev-dependencies]
criterion = "0.4.0"

# [[bench]]
# name = "decoding"
# harness = false
